source "https://rubygems.org"

ruby "2.2.2"

gem "addressable"
gem "bourbon"
gem "coffee-script"
gem "excon"
gem "fernet"
gem "multi_json"
gem "oj" # fast json
gem "pry"
gem "puma"
gem "rack"
gem "rack-flash3",     require: "rack/flash"
gem "rack-instruments"
gem "rack-ssl"
gem "rack_csrf",       require: "rack/csrf"
gem "rollbar"
gem "sinatra",         require: "sinatra/base"
gem "sinatra-contrib", require: "sinatra/namespace"
gem "sinatra-router"
gem "slim"
gem "sprockets"
gem "sprockets-sass"
gem "yui-compressor"

group :development, :test do
  #gem "debugger"
  gem "minitest"
  gem "rack-test"
  gem "rake"
  gem "rr"
  gem "timecop"
  gem "webmock"
end
