source "https://rubygems.org"

gem "addressable"
gem "airbrake"
gem "coffee-script"
gem "excon"
gem "fernet"
gem "multi_json"
gem "oj" # fast json
gem "puma"
gem "rack"
gem "rack_csrf",       require: "rack/csrf"
gem "rack-flash3",     require: "rack/flash"
gem "rack-instruments"
gem "rack-ssl"
gem "sinatra",         require: "sinatra/base"
gem "sinatra-contrib", require: "sinatra/namespace"
gem "sinatra-router"
gem "slim"
gem "compass"
gem "sprockets-sass"
gem "sprockets"
gem "yui-compressor"

group :test do
  gem "debugger"
  gem "rack-test"
  gem "rr"
  gem "webmock"
end
